In [10]:
"""1. Write a Python Program to Add Two Matrices?"""

import numpy as np
l_list1 = np.array([[16,18],[15,19]])
l_list2 = np.array([[1,4],[2,5]])
print(np.add(l_list1,l_list2))

[[17 22]
 [17 24]]


In [11]:
"""2. Write a Python Program to Multiply Two Matrices?"""
import numpy as np
l_list1 = np.array([[16,18],[15,19]])
l_list2 = np.array([[1,4],[2,5]])
print(np.multiply(l_list1,l_list2))

[[16 72]
 [30 95]]


In [12]:
"""3. Write a Python Program to Transpose a Matrix?"""
import numpy as np
l_list = np.array([[16,18],[15,19]])
print(l_list.T)



[[16 15]
 [18 19]]


In [14]:
"""4. Write a Python Program to Sort Words in Alphabetic Order?"""

st_word = input("Enter the word : ")
l_list = []
for i in st_word:
    l_list.append(i)
    l_list.sort()
    l_word = "".join(l_list)
print(l_word)


Enter the word : python
hnopty


In [4]:
"""5. Write a Python Program to Remove Punctuation From a String?"""
import re
 
test_str = "Gfg,#@ is best :@_)() for ! Geeks ;"
 
print("The original string is : ", test_str)
 
res = re.sub(r'[^\w\s]', '', test_str)
 
print("The string after punctuation filter : ", res)
            

            

The original string is :  Gfg,#@ is best :@_)() for ! Geeks ;
The string after punctuation filter :  Gfg is best _ for  Geeks 
